### ISSUE TITLE
Documentation & tests of CachePadded still have remains of the old design

### ISSUE THREAD

**Issue by HadrienG2** [crossbeam-rs/crossbeam-utils#17]
Here are some hack documentations that can be dropped now that CachePadded uses repr(align(N)) on stable:

- Struct-level: "Size and alignment" section.
- new(): "Panics" section

Unit tests for Drop and Clone can also probably be dropped, as these are automatically derived in the new design.

**Comment by stjepang** [comment]
Thank you for reporting! I've opened a PR fixing this.

> Unit tests for Drop and Clone can also probably be dropped, as these are automatically derived in the new design.

There's no harm in leaving them either. :) The tests just verify that `CachePadded` doesn't behave like `ManuallyDrop` and it doesn't memcpy the data when cloning.
