### ISSUE TITLE
ScopedThreadBuilder::spawn and Scope::spawn return different types

### ISSUE THREAD

**Issue by vitiral** [crossbeam-rs/crossbeam-utils#5]
- `Scope -------- :` [`pub fn spawn<F, T>(&self, f: F) -> ScopedJoinHandle<T>`](https://docs.rs/crossbeam-utils/0.2.2/crossbeam_utils/scoped/struct.Scope.html#method.spawn)
- `ScopedThreadBuilder:` [`fn spawn<F, T>(self, f: F) -> Result<ScopedJoinHandle<T>>`](https://docs.rs/crossbeam-utils/0.2.2/crossbeam_utils/scoped/struct.ScopedThreadBuilder.html#method.spawn)

I'm not sure if there is a justification for Builder::spawn to return an `io::Error` but `Scope::spawn` to not. If there is it should be documented why this is the case and how an error can come about, if there isn't it may be worth a breaking change.

Love the library!

**Comment by jeehoonkang** [comment]
I agree with you.  I prefer changing `Scope::spawn()` to return `io::Result<ScopedJoinHandle<T>>`, and changing `spawn_unsafe()` to return `io::Result<thread::JoinHandle<()>>`.

**Comment by vitiral** [comment]
I'm still confused about how _spawning_ a thread can return an `io::Result`? How could a thread fail to spawn... the system is overloaded?

**Comment by vitiral** [comment]
I guess someone might want to develop their application with that failure in mind! I hardly ever think of it, but resource exhaustion can certainly happen.

**Comment by jeehoonkang** [comment]
Ah, I just re-read the documentation.  [It says](https://doc.rust-lang.org/std/thread/fn.spawn.html): [`std::thread::spawn()`] "Panics if the OS fails to create a thread; use Builder::spawn to recover from such errors."  So the behavior of current `crossbeam-utils` matches with that of `std`.

**Comment by vitiral** [comment]
Gotcha! Can you add docs to that effect.

**Comment by jeehoonkang** [comment]
Closing it.  Let's discuss the documentation in #6.  Thanks!
