### ISSUE TITLE
Split crossbeam-utils into multiple crates?

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-utils#53]
This crate is growing. Now it has `AtomicCell`, `AtomicConsume`, `ShardedLock`, `CachePadded`, and scoped threads. Dependencies are growing, too: `ShardedLock` pulls in `lazy_static`, `parking_lot`, and `num_cpus` as dependencies, which might be a problem for libraries depending on `crossbeam-utils`.

There are some libraries that only need `CachePadded`, or only need scoped threads, so pulling in all the other things will be too much bloat for them. It's typically not a problem for applications to have a bunch of dependencies, but libraries care a lot about being minimal. In other words, if you're developing an application, it's okay to add the whole `crossbeam` as a dependency, but if you're writing a library, you should choose the parts of crossbeam you need.

I suggest we split up `crossbeam-utils` so that libraries can choose what to depend on more precisely. My suggestion is:

* Move `crossbeam_utils::thread` into a new crate `crossbeam-thread`.
* Move `crossbeam_utils::sync` into a new crate `crossbeam-sync` (it's supposed to be for synchronization primitives like `ShardedLock`, `WaitGroup`, and things like that).
* Keep `crossbeam_utils::atomic` in `crossbeam-utils`, although we might want to move it out in the future, too.
* Keep `CachePadded` in `crossbeam-utils`.

It's unfortunate that we need to have so many crates, but it's just the nature of the project - crossbeam is really a bunch of somewhat related tools for concurrency.

cc @Vtec234

**Comment by Thomasdezeeuw** [comment]
Can't these be features? I don't see a point in creating even more crates. But I got the overall sentiment of a growing crate.

**Comment by arthurprs** [comment]
:+1: on splitting the big ones out to their own crates or a group crate (crossbeam-sync). Mainly because of dependency bloat.

I don't have strong opinions regarding bringing everything into a single repo though. Maybe avoid it and keep the code here as there's no clear benefit in crossbeam case (IMO).

I think this was beneficial in `tokio` because the cross crate code churn was (still?) high enough that getting a green CI build was cumbersome.

**Comment by Thomasdezeeuw** [comment]
@stjepang I didn't know about features acting as a separate crate when building, good to know.

Then I'm for seperate crates, but keeping them within the same repo. Because in my opinion having 5+ small repos in harder to maintain then one bigger repo.

**Comment by Thomasdezeeuw** [comment]
Come to think of it maybe crossbeam should follow tokio and futures style. Having multiple small crates in the same repo, and then having one crossbeam crate that just imports everything. This way we you need some data struct, e.g. a channel, you can look in a single crate if crossbeam has something that fits and then just import the crate that is needed, for channels that would be crossbeam-channel.

**Comment by stjepang** [comment]
@arthurprs 

> Maybe avoid it and keep the code here as there's no clear benefit in crossbeam case (IMO).

A good reason for keeping code in a single repo is simplicity. Some users are unsure which repo they should file issues in, so they just open one in the main crossbeam repo ([example](https://github.com/crossbeam-rs/crossbeam/issues/173)), and then issues become scattered throughout multiple issue trackers...

As another example, [`futures-rs`](https://github.com/rust-lang-nursery/futures-rs) consists of multiple crates kept in a single repo, too.

**Comment by arthurprs** [comment]
@stjepang you make a good argument :+1:

**Comment by Vtec234** [comment]
> opinions on moving subcrates into the main crossbeam repository?

This makes sense, but all issues would have to be migrated and all outstanding PRs rewritten to match the new directory structure. Maybe this could be done for the 1.0 release of crossbeam? It seems that would be a good point to agree on the final organisation - I'm sure new issues will also arise before 1.0 that could guide the design.

> I suggest we split up crossbeam-utils so that libraries can choose what to depend on more precisely.

This is also reasonable, and for now we could keep all crates split from `utils` in this repo.

**Comment by Thomasdezeeuw** [comment]
@Vtec234 I count 20 issues (including this one) and 5 prs across all crossbeam repos (except crossbeam and rfs repos). So I don't think that is much of a problem and we can always start small.

I'm all for small crates inside a single repo.

**Comment by stjepang** [comment]
@Vtec234 

> This makes sense, but all issues would have to be migrated and all outstanding PRs rewritten to match the new directory structure. Maybe this could be done for the 1.0 release of crossbeam?

There are still relatively few open issues and PRs and a good chunk of them can already be merged or closed. I think migration at this point would be reasonably easy, but it might get more difficult in the future when we accumulate more issues.

> I do have to say that I like having structure-specific discussions on the relevant repo and the far lower amount of noise thanks to that.

Labels can help with organization by subcrates, though.

**Comment by stjepang** [comment]
Another argument for having a single repo:

After releasing a new version of `crossbeam-epoch`, we'd usually like to update `Cargo.toml` in other crates like `crossbeam-deque`, `crossbeam`, and so on. Bumping the version in each crate separately is painful and time-consuming. We often fall behind when it comes to such dependencies - see https://github.com/crossbeam-rs/crossbeam/issues/190 as an example.

But if we keep all crates in a single repo, then we can bump versions in all `Cargo.toml` files in a single commit. Releasing new versions becomes easier, too.

By the way, here's yet another example of a project that keeps a bunch of subcrates in a single repo :)
https://github.com/spacejam/sled/tree/master/crates

**Comment by Vtec234** [comment]
Apologies for a delayed response. You make a convincing argument, so let's do this :) I assume in that case `crossbeam-rs` would be left with two active repos, `crossbeam` and `rfcs` (since RFCs aren't versioned in the same way)? We'll just have to keep an eye on preserving a clear, hopefully acyclic dependency graph between the crates.

GitHub also has a "projects" feature to group issues, which could be very helpful alongside issue tags.

**Comment by stjepang** [comment]
> I assume in that case `crossbeam-rs` would be left with two active repos, `crossbeam` and `rfcs` (since RFCs aren't versioned in the same way)

Exactly.

> We'll just have to keep an eye on preserving a clear, hopefully acyclic dependency graph between the crates.

I'm pretty sure Cargo doesn't allow cyclic dependencies anyway. :)

**Comment by Vtec234** [comment]
> I'm pretty sure Cargo doesn't allow cyclic dependencies anyway. :)
Hm, maybe by using features to effectively split a crate in two it would be possible? Who knows :thinking:

**Comment by kpcyrd** [comment]
@Vtec234 due to the way dependency features are resolved/enabled this shouldn't be possible.

I would strongly recommend to move the crates in a single repo and use [cargo workspaces][1].

[1]: https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html

Issues like https://github.com/crossbeam-rs/crossbeam-deque/issues/17 and https://github.com/crossbeam-rs/crossbeam/issues/190 are causing problems for distros, right now [cc] is blocked from transitioning to debian testing. This could've been discovered before the release with workspaces and CI.

[cc]: https://tracker.debian.org/pkg/rust-cc

I would also argue that splitting into too many crates has disadvantages as well: It's adding workload to downstream and adds performance overhead when dynamic linking becomes common.

**Comment by ghost** [comment]
> I would also argue that splitting into too many crates has disadvantages as well: It's adding workload to downstream and adds performance overhead when dynamic linking becomes common.

Fair enough. Here's a more conservative proposal than the one in [original comment](https://github.com/crossbeam-rs/crossbeam-utils/issues/53#issue-370091676):

* Move the `crossbeam_utils::sync` module into `crossbeam`.

Perhaps a good strategy is to put all new stuff we create into `crossbeam` by default and only move them into smaller subcrates when other library writers request it.
