### ISSUE TITLE
Document what happens when internal thread panics when joined

### ISSUE THREAD

**Issue by vitiral** [crossbeam-rs/crossbeam-utils#6]
It is currently undocumented what happens when joining a panic-ed thread with [ScopedJoinHandle::join](https://docs.rs/crossbeam-utils/0.2.2/crossbeam_utils/scoped/struct.ScopedJoinHandle.html#method.join).

[`std::thread::JoinHandle::join`](https://doc.rust-lang.org/std/thread/struct.JoinHandle.html#method.join) returns `-> Result<T>` instead of `-> T`, which returns the result of the panic.

BTW, I think automatically panicing is fine behavior.

**Comment by jeehoonkang** [comment]
I'd like to just mimic the behavior of `std::thread` here, by returning the result of the panic.

I think #5 is closely related to this issue.  Thanks for reporting these!
